### ISSUE TITLE
Export fails when passing `-c`

### ISSUE THREAD

**Issue by LMESTM** [ARMmbed/mbed-os-example-blinky#86]
#description

I imported this example in my environment 
`mbed` import `mbed-os-example-blinky`

Compiled ok:
` mbed compile -t IAR -m NUCLEO_L476RG `

Trying export fails:
```
$ mbed export -i IAR -m NUCLEO_L476RG  -c -vv
Traceback (most recent call last):
  File "C:\Data\Workspace\mbed-os-example-blinky\mbed-os\tools\project.py", line 256, in <module>
    main()
  File "C:\Data\Workspace\mbed-os-example-blinky\mbed-os\tools\project.py", line 248, in main
    rmtree(BUILD_DIR)
  File "c:\python27\lib\shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "c:\python27\lib\shutil.py", line 237, in rmtree
    names = os.listdir(path)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Data\\Workspace\\mbed-os-example-blinky\\mbed-os\\BUILD/*.*'
[mbed] Working path "C:\Data\Workspace\mbed-os-example-blinky" (program)
[mbed] Exec "c:\python27\python.exe -u C:\Data\Workspace\mbed-os-example-blinky\mbed-os\tools\project.py -i iar -m NUCLEO_L476RG -c --source ." in C:\Data\Workspace\mbed-os-example-blinky
[mbed] ERROR: "c:\python27\python.exe" returned error code 1.
[mbed] ERROR: Command "c:\python27\python.exe -u C:\Data\Workspace\mbed-os-example-blinky\mbed-os\tools\project.py -i iar -m NUCLEO_L476RG -c --source ." in "C:\Data\Workspace\mbed-os-example-blinky"
---
```

Windows OS, with MINGW64

**Comment by 0xc0170** [comment]
I reproduced the issue. The traceback is caused by `-c` argument , and build is not there. This should be handled normally.

cc @theotherjimmy

**Comment by theotherjimmy** [comment]
Agreed. Let me see if this is cross platform.

**Comment by theotherjimmy** [comment]
Nope. Seems like it's a Windows only issue. Sorry.

**Comment by theotherjimmy** [comment]
@LMESTM Could you open an issue for this on mbed-os? This is a problem with all `mbed export -c` which is part of the Mbed OS tools.

**Comment by 0xc0170** [comment]
> @LMESTM Could you open an issue for this on mbed-os? This is a problem with all mbed export -c which is part of the Mbed OS tools.

@LMESTM bump

**Comment by LMESTM** [comment]
Done: 
https://github.com/ARMmbed/mbed-os/issues/5276
